module MiddlemanResponseMapperUtility
  module ThorRC
    SUCCESSFUL                      = '0000'
    UNAUTHENTICATED                 = '0004'
    OTHER_ERROR                     = '0005'
    INVALID_ACCESS_TIME             = '0008'
    INACTIVE_USER                   = '0009'
    INVALID_TRANSACTION_AMOUNT      = '0013'
    UNKNOWN_CUSTOMER_ID             = '0014'
    UNKNOWN_METER_NUMBER            = '0015'
    CUSTOMER_HAS_OUTSTANDING_BILL   = '0017'
    INVALID_MESSAGE                 = '0030'
    UNKNOWN_PRODUCT                 = '0033'
    UNREGISTERED_USER               = '0035'
    DUPLICATE_ORDER_ID              = '0036'
    AMOUNT_BELOW_MINIMUM            = '0041'
    AMOUNT_ABOVE_MAXIMUM            = '0042'
    NEW_POWER_CATEGORY_IS_SMALLER   = '0043'
    NEW_POWER_CATEGORY_INVALID      = '0044'
    INVALID_ADMIN_AMOUNT            = '0045'
    INSUFFICIENT_BALANCE            = '0046'
    KWH_OVERLIMIT                   = '0047'
    REQUEST_EXPIRED                 = '0048'
    NO_PAYMENT                      = '0063'
    TIMEOUT                         = '0068'
    CUSTOMER_SUSPENDED              = '0077'
    BILLS_ALREADY_PAID              = '0088'
    BILLS_NOT_AVAILABLE             = '0089'
    CUT_OFF                         = '0090'
    DATABASE_ERROR                  = '0091'
    ORDER_ID_NOT_FOUND              = '0092'
    REVERSAL                        = '0094'
    REFERENCE_NUMBER_INVALID        = '0098'
    UNKNOWN_ERROR                   = '0100'
  end
end