# frozen_string_literal: true

module MiddlemanResponseMapperUtility
  module VisaRC
    # success in visa has many forms
    ACCEPTED = 'VISA_ACCEPTED' # success status
    SUCCESS_OCT = 'VISA_100' # success oct
    SUCCESS_PROCESSOR = 'VISA_00' # success processor

    TIMEOUT = 'timeout' # genereal timeout
    NO_REF_CODE = 'VISA_NO_REF_CODE'
    NO_TOKEN = 'VISA_NO_TOKEN'
    ERROR = 'VISA_ERROR'
    INVALID_REQUEST = 'VISA_INVALID_REQUEST'

    MISSING_FIELDS = 'VISA_101'
    INVALID_DATA = 'VISA_102'
    INVALID_MERCHANT_REF_CODE = 'VISA_104'
    GENERAL_SYSTEM_FAILURE = 'VISA_150'
    OCT_DISABLED = 'VISA_153'
    BANK_HAS_QUESTIONS = 'VISA_201'
    EXPIRED_CARDS = 'VISA_202'
    BANK_GENERAL_DECLINE = 'VISA_203'
    STOLEN_OR_LOST_CARD = 'VISA_205'
    INACTIVE_CARD = 'VISA_208'
    INVALID_ACCOUNT_NUMBER = 'VISA_231'
    PROCESSOR_GENERAL_DECLINE = 'VISA_233'
    CYBERSOURCE_ACCOUNT_INCORRECT_INFO = 'VISA_234'
    INVALID_CARD_TYPE = 'VISA_240'
    PAYMENT_PROCESS_TIMEOUT = 'VISA_250'
    TEMPORARY_AGGREGATOR_NOT_ACCEPTING = 'VISA_490'
    AGGREGATOR_NOT_ACCEPTING = 'VISA_491'
    ISSUER_DECLINE_TRANSACTION = 'VISA_12'
    AMOUNT_EXCEED_LIMIT_OCT = 'VISA_13'
    CARDHOLDER_INVALID_FOR_OCT = 'VISA_57'
    CUMULATIVE_TOTAL_AMOUNT_LIMIT_EXCEEDED = 'VISA_61'
    COUNTRY_RESTRICTED_CARD = 'VISA_62'
    ANTI_MONEY_LAUNDERING_REQUIREMENTS = 'VISA_64'
    CUMULATIVE_TOTAL_COUNT_LIMIT_EXCEEDED = 'VISA_65'
    ISSUER_UNAVAILABLE = 'VISA_91'
    VIOLATES_LAW = 'VISA_93'
    DUPLICATE_TRANSACTION = 'VISA_94'
    OCT_GENERAL_ERROR = 'VISA_96'
  end
end
