# frozen_string_literal: true

module Channel
  module Config
    include Postpaid::Constant
    # partner product id
    PRODUCT_ID = {
      ELECTRICITY_PRODUCT => ENV['POSTPAID_PRODUCT'].to_i,
      BPJS_KESEHATAN_PRODUCT => ENV['BPJS_KESEHATAN_PRODUCT'].to_i,
      PDAM_PRODUCT => ENV['PDAM_PRODUCT'].to_i
    }

    # General Configurations for Partner
    DEFAULT_TIMEOUT_TIME_SECONDS = 20
    DEFAULT_RETRY_ATTEMPTS       = 5

    # transaction type
    # please add new method transaction_type for this
    TRANSACTION_TYPE = {
      ELECTRICITY_PRODUCT => 'electricity_postpaid',
      BPJS_KESEHATAN_PRODUCT => 'bpjs-kesehatan',
      BPJS_KETENAGAKERJAAN_PRODUCT => 'bpjs-ketenagakerjaan',
      PDAM_PRODUCT => 'pdam',
      PHONE_CREDIT_PRODUCT => 'phone-credit-postpaid',
      CREDIT_CARD_BILL_PRODUCT => 'credit-card-bill',
      VEHICLE_TAX_PRODUCT => 'vehicle-tax',
    }

    SEPULSA_CONFIG    = YAML.load(ERB.new(File.new("#{Rails.root}/config/sepulsa.yml").read).result)[Rails.env]

    if ENV['SEPULSA_WIREMOCK'].present?
      if Rails.env.production?
        SEPULSA_ENDPOINT = 'http://wiremock-box.preproduction.bl-cloud.internal./sepulsa-mock/'
      else
        SEPULSA_ENDPOINT = 'http://localhost:8081/sepulsa-mock/'
      end
    else
      SEPULSA_ENDPOINT  = SEPULSA_CONFIG['host']
    end

    SEPULSA_AUTH_KEY  = Base64.strict_encode64("#{SEPULSA_CONFIG['username']}:#{SEPULSA_CONFIG['server_key']}")
    MITRA_SEPULSA_AUTH_KEY  = Base64.strict_encode64("#{ENV['MITRA_SEPULSA_USERNAME']}:#{ENV['MITRA_SEPULSA_KEY']}")

    BUKALAPAK_ENDPOINT = ENV['BUKALAPAK_URL']
    BUKALAPAK_HOST = ENV['MOTHERHSIP_INTERNAL_HOST']
    BUKALAPAK_AUTH_KEY = Base64.strict_encode64("#{ENV['OLYMPUS_USERNAME']}:#{ENV['OLYMPUS_PASSWORD']}")
    BUKALAPAK_INTERNAL_INVOICE_URL = ENV['BUKALAPAK_INTERNAL_INVOICE_URL']

    BNI_ENDPOINT = ENV['BNI_ENDPOINT']
    BNI_XAUTH_KEY = Base64.strict_encode64("#{ENV['BNI_USERNAME']}:#{ENV['BNI_PASSWORD']}")
    BNI_BASIC_AUTH_KEY = Base64.strict_encode64("#{ENV['BNI_CLIENT_ID']}:#{ENV['BNI_CLIENT_SECRET']}")
    BNI_DEALER_ID = ENV['BNI_DEALER_ID'].to_s
    BNI_KODE_MITRA = ENV['BNI_KODE_MITRA'].to_s
    BNI_KODE_LOKET = ENV['BNI_KODE_LOKET'].to_s
    BNI_KODE_CABANG = ENV['BNI_KODE_CABANG'].to_s
    BNI_PIN_TRANSAKSI = ENV['BNI_PIN_TRANSAKSI'].to_s
    BNI_ACCOUNT_NUM = ENV['BNI_ACCOUNT_NUM'].to_s
    BNI_BILLER_CODE = 'BNI'

    BUKOPIN_HOST = ENV['BUKOPIN_HOST']
    BUKOPIN_PORT = ENV['BUKOPIN_PORT']
    BUKOPIN_PRIVATE_KEY = ENV['BUKOPIN_PRIVATE_KEY']
    BUKOPIN_PARTNER_CENTRAL_ID = ENV['BUKOPIN_PARTNER_CENTRAL_ID']
    BUKOPIN_USER_ID = ENV['BUKOPIN_USER_ID']

    BUKOPIN_HOST_BMI = ENV.fetch('BUKOPIN_HOST_BMI')
    BUKOPIN_PORT_BMI = ENV.fetch('BUKOPIN_PORT_BMI')
    BUKOPIN_PRIVATE_KEY_BMI = ENV.fetch('BUKOPIN_PRIVATE_KEY_BMI')
    BUKOPIN_PARTNER_CENTRAL_ID_BMI = ENV.fetch('BUKOPIN_PARTNER_CENTRAL_ID_BMI')

    DJI_BPJS_KESEHATAN_PRODUCT_CODE = ENV['BPJS_KESEHATAN_DJI_PRODUCT']
    DJI_HOST = ENV['DJI_HOST']
    DJI_PORT = ENV['DJI_PORT']
    DJI_MULTIBILLER_HOST = ENV['DJI_MULTIBILLER_HOST']
    DJI_MULTIBILLER_PORT = ENV['DJI_MULTIBILLER_PORT']

    RECURSIVE_ENDPOINT = ENV['RECURSIVE_URL']
    RECURSIVE_AUTH_KEY = Base64.strict_encode64("#{ENV['RECURSIVE_USERNAME']}:#{ENV['RECURSIVE_PASSWORD']}")

    TELOLET_AUTH_KEY = Base64.strict_encode64("#{ENV['TELOLET_USERNAME']}:#{ENV['TELOLET_PASSWORD']}")
    TELOLET_URL = ENV['TELOLET_URL']

    ALERT_BOT_URL = "https://tukubot.herokuapp.com:443/notify-bni/unsufficient-balance"
    ALERT_BOT_HOST = "tukubot.herokuapp.com:443"

    BTS_KUBE_AUTH_KEY = Base64.strict_encode64("#{ENV['BTS_KUBE_USERNAME']}:#{ENV['BTS_KUBE_PASSWORD']}")
    BTS_KUBE_URL = ENV['BTS_KUBE_URL']
    BTS_KUBE_CALLBACK_URL = ENV['BTS_KUBE_CALLBACK_URL']

    VISA_CYBS_MERCHANT_ID                  = ENV['VISA_CYBS_MERCHANT_ID'] # 'bukalapak_com'
    VISA_CYBS_ACCESS_KEY                   = ENV['VISA_CYBS_ACCESS_KEY'] # '7cb88fa24ffb30e79e10949ced57a23c'
    VISA_CYBS_SECRET_KEY                   = ENV['VISA_CYBS_SECRET_KEY'] # 'a217cf259e6d454eb0d9dac76dbc3b6cf704fe2de8d4423f84a65e3f5f59f4eca3efbf481a6a49ae8d0a2a58d723f926518f89ed59514e1285eba4338b50bfcc8ba24c861174453aa111f72c963a52744458f1501f4e42fa8acf473d84bdd6762cdba48d2fcb4c918a0c65f64675bf581acbc48449af4227a5a6a233ee882be9'
    VISA_CYBS_API_KEY                      = ENV['VISA_CYBS_API_KEY'] # '48404ad9-efb7-419b-b841-8f7a01b547e7'
    VISA_CYBS_API_SHARED_SECRET_KEY        = ENV['VISA_CYBS_API_SHARED_SECRET_KEY'] # '7fPJo/HP8SmzbN+ozJ+VtHD2p6qRgYrZ8xlq1Q6uS8A='
    VISA_CYBS_SECURE_ACCEPTANCE_PROFILE_ID = ENV['VISA_CYBS_SECURE_ACCEPTANCE_PROFILE_ID'] # "C3396489-5C91-4188-987C-1BB5B9C3C687"
    VISA_CYBS_TOKEN_VAULT_PROFILE_ID       = ENV['VISA_CYBS_TOKEN_VAULT_PROFILE_ID'] # "0739261B-C577-4AF8-8D0D-6870A4C4AFBD"
    VISA_WIREMOCK                          = ENV['VISA_WIREMOCK'] # preprod, localhost

    case VISA_WIREMOCK
    when 'preprod', 'preproduction'
      VISA_CYBS_API_HOST  = 'wiremock-box.preproduction.bl-cloud.internal./credit-card-bills/visa'
      VISA_CYBS_TOKEN_URL = "http://#{VISA_CYBS_API_HOST}/token"
    when 'local', 'localhost'
      VISA_CYBS_API_HOST  = 'localhost:8080/credit-card-bills/visa'
      VISA_CYBS_TOKEN_URL = "http://#{VISA_CYBS_API_HOST}/token"
    else
      VISA_CYBS_TOKEN_URL = ENV['VISA_CYBS_TOKEN_URL'] # 'https://testsecureacceptance.cybersource.com/silent/token/create'
      VISA_CYBS_API_HOST  = ENV['VISA_CYBS_API_HOST'] # 'apitest.cybersource.com'
    end

    AYOCONNECT_HOST             = ENV['AYOCONNECT_HOST']
    AYOCONNECT_API_KEY          = ENV['AYOCONNECT_API_KEY']
    AYOCONNECT_API_SECRET       = ENV['AYOCONNECT_API_SECRET']
    AYOCONNECT_MITRA_API_KEY    = ENV['AYOCONNECT_MITRA_API_KEY']
    AYOCONNECT_MITRA_API_SECRET = ENV['AYOCONNECT_MITRA_API_SECRET']

    TEKTAYA_HOST        = ENV['TEKTAYA_HOST']

    TEKTAYA_BL_USER_ID  = ENV['TEKTAYA_BL_USER_ID']
    TEKTAYA_BL_PASSWORD = ENV['TEKTAYA_BL_PASSWORD']
    TEKTAYA_BL_BIT62    = ENV['TEKTAYA_BL_BIT62']

    TEKTAYA_BMI_USER_ID  = ENV['TEKTAYA_BMI_USER_ID']
    TEKTAYA_BMI_PASSWORD = ENV['TEKTAYA_BMI_PASSWORD']
    TEKTAYA_BMI_BIT62    = ENV['TEKTAYA_BMI_BIT62']

    TEKTAYA_BMI_BUKACONNECT_USER_ID  = ENV['TEKTAYA_BMI_BUKACONNECT_USER_ID']
    TEKTAYA_BMI_BUKACONNECT_PASSWORD = ENV['TEKTAYA_BMI_BUKACONNECT_PASSWORD']
    TEKTAYA_BMI_BUKACONNECT_BIT62    = ENV['TEKTAYA_BMI_BUKACONNECT_BIT62']

    TEKTAYA_POSTPAID_URL  = ENV['TEKTAYA_POSTPAID_URL']
    TEKTAYA_LOGIN_URL     = ENV['TEKTAYA_LOGIN_URL']

    MIDDLEMAN_ENDPOINT = ENV.fetch('MIDDLEMAN_URL')
    MIDDLEMAN_AUTH_KEY = Base64.strict_encode64("#{ENV['MIDDLEMAN_USERNAME']}:#{ENV['MIDDLEMAN_PASSWORD']}")

    # [REST-2571] Configs for New BNI API
    NEW_BNI_ACCESS_TOKEN_URL = ENV['NEW_BNI_ACCESS_TOKEN_URL']
    NEW_BNI_API_KEY = ENV['NEW_BNI_API_KEY']
    NEW_BNI_API_SECRET_KEY = ENV['NEW_BNI_API_SECRET_KEY']
    NEW_BNI_TOKEN_BASIC_USERNAME = ENV['NEW_BNI_TOKEN_BASIC_USERNAME']
    NEW_BNI_TOKEN_BASIC_PASSWORD = ENV['NEW_BNI_TOKEN_BASIC_PASSWORD']
    NEW_BNI_ACCOUNT_NUM = ENV['NEW_BNI_ACCOUNT_NUM']
    NEW_BNI_PAYMENT_NON_BNI_URL = ENV['NEW_BNI_PAYMENT_NON_BNI_URL']
    NEW_BNI_INQUIRY_URL = ENV['NEW_BNI_INQUIRY_URL']
    NEW_BNI_PAYMENT_BNI_URL = ENV['NEW_BNI_PAYMENT_BNI_URL']

    # THOR
    THOR_HOST          = ENV['THOR_HOST']
    THOR_AUTH_HOST     = ENV['THOR_AUTH_HOST']
    THOR_CLIENT_ID     = ENV['THOR_CLIENT_ID']
    THOR_CLIENT_SECRET = ENV['THOR_CLIENT_SECRET']
  end
end
